/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WelcomeImport } from './routes/welcome'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as DashboardIndexImport } from './routes/_dashboard.index'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as DashboardUsersImport } from './routes/_dashboard.users'
import { Route as DashboardRoomsImport } from './routes/_dashboard.rooms'
import { Route as DashboardInvitationsImport } from './routes/_dashboard.invitations'
import { Route as DashboardAccountImport } from './routes/_dashboard.account'
import { Route as DashboardUserUserIdUserNameImport } from './routes/_dashboard.user/$userId.$userName'
import { Route as DashboardRoomRoomIdRoomNameImport } from './routes/_dashboard.room/$roomId.$roomName'
import { Route as DashboardRoomRoomIdRoomNameMembersImport } from './routes/_dashboard.room/$roomId.$roomName.members'

// Create/Update Routes

const WelcomeRoute = WelcomeImport.update({
  path: '/welcome',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersRoute = DashboardUsersImport.update({
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardRoomsRoute = DashboardRoomsImport.update({
  path: '/rooms',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardInvitationsRoute = DashboardInvitationsImport.update({
  path: '/invitations',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAccountRoute = DashboardAccountImport.update({
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUserUserIdUserNameRoute =
  DashboardUserUserIdUserNameImport.update({
    path: '/user/$userId/$userName',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardRoomRoomIdRoomNameRoute =
  DashboardRoomRoomIdRoomNameImport.update({
    path: '/room/$roomId/$roomName',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardRoomRoomIdRoomNameMembersRoute =
  DashboardRoomRoomIdRoomNameMembersImport.update({
    path: '/members',
    getParentRoute: () => DashboardRoomRoomIdRoomNameRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/account': {
      id: '/_dashboard/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof DashboardAccountImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/invitations': {
      id: '/_dashboard/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof DashboardInvitationsImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/rooms': {
      id: '/_dashboard/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof DashboardRoomsImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersImport
      parentRoute: typeof DashboardImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/room/$roomId/$roomName': {
      id: '/_dashboard/room/$roomId/$roomName'
      path: '/room/$roomId/$roomName'
      fullPath: '/room/$roomId/$roomName'
      preLoaderRoute: typeof DashboardRoomRoomIdRoomNameImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/user/$userId/$userName': {
      id: '/_dashboard/user/$userId/$userName'
      path: '/user/$userId/$userName'
      fullPath: '/user/$userId/$userName'
      preLoaderRoute: typeof DashboardUserUserIdUserNameImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/room/$roomId/$roomName/members': {
      id: '/_dashboard/room/$roomId/$roomName/members'
      path: '/members'
      fullPath: '/room/$roomId/$roomName/members'
      preLoaderRoute: typeof DashboardRoomRoomIdRoomNameMembersImport
      parentRoute: typeof DashboardRoomRoomIdRoomNameImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  DashboardRoute: DashboardRoute.addChildren({
    DashboardAccountRoute,
    DashboardInvitationsRoute,
    DashboardRoomsRoute,
    DashboardUsersRoute,
    DashboardIndexRoute,
    DashboardRoomRoomIdRoomNameRoute:
      DashboardRoomRoomIdRoomNameRoute.addChildren({
        DashboardRoomRoomIdRoomNameMembersRoute,
      }),
    DashboardUserUserIdUserNameRoute,
  }),
  WelcomeRoute,
  AuthSigninRoute,
  AuthSignupRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_dashboard",
        "/welcome",
        "/auth/signin",
        "/auth/signup"
      ]
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/account",
        "/_dashboard/invitations",
        "/_dashboard/rooms",
        "/_dashboard/users",
        "/_dashboard/",
        "/_dashboard/room/$roomId/$roomName",
        "/_dashboard/user/$userId/$userName"
      ]
    },
    "/welcome": {
      "filePath": "welcome.tsx"
    },
    "/_dashboard/account": {
      "filePath": "_dashboard.account.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/invitations": {
      "filePath": "_dashboard.invitations.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/rooms": {
      "filePath": "_dashboard.rooms.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/users": {
      "filePath": "_dashboard.users.tsx",
      "parent": "/_dashboard"
    },
    "/auth/signin": {
      "filePath": "auth/signin.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/_dashboard/": {
      "filePath": "_dashboard.index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/room/$roomId/$roomName": {
      "filePath": "_dashboard.room/$roomId.$roomName.tsx",
      "parent": "/_dashboard",
      "children": [
        "/_dashboard/room/$roomId/$roomName/members"
      ]
    },
    "/_dashboard/user/$userId/$userName": {
      "filePath": "_dashboard.user/$userId.$userName.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/room/$roomId/$roomName/members": {
      "filePath": "_dashboard.room/$roomId.$roomName.members.tsx",
      "parent": "/_dashboard/room/$roomId/$roomName"
    }
  }
}
ROUTE_MANIFEST_END */
